name: quick_video_player
description: "Reusable network video player and vertical short-form video feed."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.1 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  get: ^4.7.2
  video_player: ^2.11.1
  visibility_detector: ^0.4.0+2
  wakelock_plus: ^1.5.1
  infinite_scroll_pagination: ^5.1.1
  share_plus: ">=10.1.0 <13.0.0"
  html: ^0.15.4

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
